root      = "."
tmp_dir   = "/tmp/air"

[build]
  cmd         = "go build -o /tmp/air/main ./cmd/gyrifi"
  bin         = "/tmp/air/main"
  include_ext = ["go", "sql"]
  exclude_dir = ["vendor", "tests"]
  delay       = 500      # ms to wait after a change before rebuilding

[log]
  time = true

[color]
  main    = "magenta"
  watcher = "cyan"
  build   = "yellow"
  runner  = "green"
